### ISSUE TITLE
Probabile file da aggiungere al .gitignore

### ISSUE THREAD

**Issue by mrksoftware** [andrekiba/IsiiSports#4]
Durante il merge della mia branch su master ho dovuto risolvere una ventina di conflitti sul file IsiiSports/Droid/Resources/Resource.Designer.cs

Visto che è un file auto generato, forse sarebbe meglio aggiungerlo al .gitignore per evitare di avere problemi ad ogni commit.

Cosa ne pensi?

**Comment by andrekiba** [comment]
si penso si possa mettere nel .gitignore, Xamarin dovrebbe rigenerarlo...forse :-) https://forums.xamarin.com/discussion/65403/can-the-resource-designer-cs-files-be-ignored-in-source-control

**Comment by andrekiba** [comment]
Fatto 😀
