### ISSUE TITLE
[SOLVED] Strano errore durante la fase di build del progetto Xamarin.Droid

### ISSUE THREAD

**Issue by mrksoftware** [andrekiba/IsiiSports#6]
![image](https://cloud.githubusercontent.com/assets/7292153/23230331/d5301aba-f943-11e6-8358-80f426f2bb39.png)

**Comment by mrksoftware** [comment]
Soluzione trovata qui: https://forums.xamarin.com/discussion/2132/java-heap-space-outofmemoryerror-when-binding-a-big-jar

**Comment by andrekiba** [comment]
Yes mi sento dimenticato di modificarlo nel proprietà del progetto, succede spesso...

**Comment by mrksoftware** [comment]
No problem! L'ho aggiunto anche per lasciare qualcosa di scritto nel caso mi succedesse di nuovo in futuro! ;)
