### ISSUE TITLE
Navigazione da GamesPage a GamePage

### ISSUE THREAD

**Issue by mrksoftware** [andrekiba/IsiiSports#8]
Quando navighiamo da GamesPage a GamePage rimane la schermata con i tab.
Occorre aggiungere un nuovo NavigationContainer?

Esempio:
![image](https://cloud.githubusercontent.com/assets/7292153/23232441/8c6b4342-f94b-11e6-9c0f-e369c9bd8584.png)

**Comment by mrksoftware** [comment]
Lascio questa issue come promemoria, non c'è nessuna urgenza al momento.

**Comment by mrksoftware** [comment]
per intenderci mi aspettavo qualcosa del genere anche qui su android: https://github.com/pocheshire/BottomNavigationBar 
Fatto in questo modo non mi sembra il massimo dal punto di vista dell'UX.

Chiaramente non sono cose che dobbiamo correggere per la presentazione all'ISII :stuck_out_tongue_closed_eyes:  era giusto per parlarne! :relaxed:

**Comment by andrekiba** [comment]
Sistemata! :-)
